server:
  port: ${SERVER_PORT}

spring:
  application:
    name: BalaGuide
  devtools:
    add-properties: false

  # Database Configuration
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Config Kafka-server
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    # Config Kafka producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Config Kafka consumer
    consumer:
      group-id: email
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  # Config email
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: ${MAIL_PORT}
            class: javax.net.ssl.SSLSocketFactory

# Token key
token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  lifetime : ${TOKEN_LIFETIME}