server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: BalaGuide
  devtools:
    add-properties: false
    restart:
      enabled: false

  # Database Configuration
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false     # разрешаем очистку базы
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Config Kafka-server
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    # Config Kafka producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Config Kafka consumer
    consumer:
      group-id: email
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  # Config email
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: ${MAIL_PORT}
            class: javax.net.ssl.SSLSocketFactory

# Token key
token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  lifetime: ${TOKEN_LIFETIME}

logging:
  level:
    org.flywaydb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, flyway, info, prometheus
  endpoint:
    health:
      show-details: always

sftp:
  url: ${SFTP_URL}
  path: ${SFTP_PATH}
